### PR TITLE
Pr 15

### PR DESCRIPTION
**Pull request by stefanpenner**
rebase #15

### CODE REVIEW

**Comment by yannickglt** [comment]
Is there a chance that this PR be merged @rwjblue? Else I will have to use the @stefanpenner 's branch...

**Comment by stefanpenner** [comment]
I don't even remember writing this :p

**Comment by yannickglt** [comment]
Thank you @rwjblue @stefanpenner and @ramybenaroya :)

**Comment by ruslanmogilevskiy** [comment]
Could someone please update the broccoli-jshint NPM package with this new and very useful feature.

**Comment by SSS2557** [comment]
@rwjblue @stefanpenner 
yes its been a while...looks like, its still not published. This is really required

**Comment by stefanpenner** [comment]
@SSS2557 it was published, about 2 months ago.

**Comment by SSS2557** [comment]
oh!
sorry about the call out then :) 

For some reason, I can't get it to work, looks like we may have a bug :cry: 

I'll dig in to see whats up and keep you posted in any case

**Comment by stefanpenner** [comment]
> I'll dig in to see whats up and keep you posted in any case

:+1:

**Pull request merged**
