### PR TITLE
Use cauliflower-filter instead of broccoli-filter

### PR DESCRIPTION
**Pull request by pete-the-pete**
Updated plugin to use cauliflower-filter and rebuild() instead of write().

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like this will need some tweaking (I just merged https://github.com/rwjblue/broccoli-jshint/pull/26).

**Comment by pete-the-pete** [comment]
Ya, i'll look into it.

**Comment by joliss** [comment]
Cauliflower-filter is a bit behind, API-wise, until we finish up https://github.com/caitp/cauliflower-filter/pull/15.

**Comment by pete-the-pete** [comment]
this can be closed since broccoli-filter is updated, this just needs a version bump

**Pull request closed without merging**
